= Daily SVN usage
Kacper Bak <http://kacperbak.de>
:toc:

:author: Kacper Bak
:homepage: http://kacperbak.de
:imagesdir: ./img
:docinfo1: docinfo-footer.html

Tested against http://www.collab.net/products/subversion[CSVN] instance located on Lubuntu 14.04 LTS x64 `~/csvn`.
Start the console with `~/csvn/bin/csvn start` command. After successfull launch the address to the browser interface is going to be displayed.
....
CSVN Console is ready at http://localhost:3343/csvn
....
The console can also be launched on system startup, see the README file for details.
Using subversion with the default configuration, login as admin and run the server using the `Start` button.


== CLI commands

=== Ckeckout a repository
....
svn checkout http://localhost:3343/csvn/project1
....

=== Ckeckout a specific revision
....
svn checkout -r 123 http://localhost:3343/csvn/project1
....

=== Commit changes
....
svn commit . -m "my commit message"
....

=== Create branch and commit
....
svn cp trunk branches/feature-branch-XYZ
svn commit . -m "feature-branch-XYZ added"
....

=== Remove branch and commit
....
svn rm --force trunk branches/feature-branch-XYZ
svn commit . -m "feature-branch-XYZ removed"
....

=== List last 10 commits
....
svn log -l 10 .
....
-l maximum number of log entries

=== List everything in ascending order
....
svn log -r 1:HEAD
....

=== List everything in descending order
....
svn log -r HEAD:1
....

=== Print commit statistics
....
svn log -v --xml | grep '<author.*/author>' | sort $* | uniq -c | sort -rn
....

=== Ignore a single directory in SVN
Ignore a directory with the name `workdir`.
Run this command from the directory that contains `workdir` e.g.: `trunk`.
....
cd trunk
svn propset svn:ignore workdir .
....
Now check that the folder has been ignored:
....
svn status --no-ignore
....
You should see the following output, the `I` indicates that this directory is now ready to be ignored:
....
$ svn status --no-ignore
 M      trunk
I       trunk/workdir
....
Commit your changes to apply.
....
svn commit . -m "'workdir' excluded from versioning."
....


