
= Spring Boot
Kacper Bak <kontakt@kacperbak.de>

:toc:
:toc-placement: manual

toc::[]

== Features
* Create stand-alone Spring applications
* Embed Tomcat or Jetty directly (no need to deploy WAR files)
* Absolutely no code generation and no requirement for XML configuration


== Notes

=== Building Java Projects with Maven

.execute the compile goal
Resulting in compiled .class files in the target/classes directory. +mvn compile+

....
.
├── gs-maven.iml
├── pom.xml
├── src
│   └── main
│       └── java
│           └── hello
│               ├── Greeter.java
│               └── HelloWorld.java
└── target
    └── classes
        └── hello
            ├── Greeter.class
            └── HelloWorld.class
....

.execute the package goal
The package goal will *compile* your Java code, run any *tests*, and finish by packaging the code up in a *JAR* file within the _target_ directory.
+mvn package+

....
.
├── dependency-reduced-pom.xml
├── gs-maven.iml
├── pom.xml
├── src
│   └── main
│       └── java
│           └── hello
│               ├── Greeter.java
│               └── HelloWorld.java
└── target
    ├── classes
    │   └── hello
    │       ├── Greeter.class
    │       └── HelloWorld.class
    ├── gs-maven-0.1.0.jar
    ├── maven-archiver
    │   └── pom.properties
    ├── original-gs-maven-0.1.0.jar
    └── surefire

....

.execute the install goal
The install goal will *compile*, *test*, and *package* your project’s code and then *copy* it into the local dependency repository, *ready for another project to reference it as a dependency*.

=== maven shade plugin

.Problem
Aggregating classes/resources from several artifacts into one uber JAR is straight forward as long as there is no overlap.
Otherwise, some kind of logic to merge resources from several JARs is required. This is where resource transformers kick in.
footnote:[http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ManifestResourceTransformer]

In this case: _ManifestResourceTransformer_ +
The ManifestResourceTransformer allows existing entries in the MANIFEST to be replaced and new entries added.

.But what is the MANIFEST file?
* Define the entry point of the Application, make the Jar executable. (MainClass has to be set)
* Add project dependency classpath.
footnote:[http://www.mkyong.com/maven/how-to-create-a-manifest-file-with-maven/]
